### ISSUE TITLE
[FEATURE] - [Skills] - Get base stats

### ISSUE THREAD

**Issue by Kirattus** [lucasmonstrox/tibiapi#12]
**Is your feature request related to a problem? Please describe.**
not applicable

**Describe the solution you'd like**
I need to get base stats to do a simple runeMaker with my character, can u do something to return these values?

**Describe alternatives you've considered**
not applicable

**Additional context**
not applicable

**Comment by lucasmonstrox** [comment]
@Kirattus is very hard to make whole information available, Im doing one by one.
