### ISSUE TITLE
[FEATURE] - Cap value

### ISSUE THREAD

**Issue by raphlmiranda** [lucasmonstrox/tibiapi#14]
**Is your feature request related to a problem? Please describe.**
not applicable

**Describe the solution you'd like**
get a cap value and return in integer number

**Describe alternatives you've considered**
not applicable

**Additional context**
not applicable

**Comment by lucasmonstrox** [comment]
@raphlmiranda sometimes `None` will be returned because sometimes skills container is not open, is not scrolled in cap area. I will implement it today.
