### ISSUE TITLE
[FEATURE] - [Skills] - "Level" with percent (if a bar is avaliable)

### ISSUE THREAD

**Issue by Kirattus** [lucasmonstrox/tibiapi#2]
**Is your feature request related to a problem? Please describe.**
not applicable

**Describe the solution you'd like**
If a bar is showing bellow of the "Value of", calcule the % and return the value.

**Describe alternatives you've considered**
A bug may occur due to the relative anchor point within the skill container (any type with bar available).
Get the value finding by the label of ur own type, this will make the values ​​more accurate for problems with layout variations caused by the user.

**Additional context**
can be replicated for all information with an available bar

**Comment by lucasmonstrox** [comment]
A method to determine if level bar is open has already been done:

https://github.com/lucasmonstrox/tibiapi/blob/f5fd71202309f5a244fa19fbe4ffbbebc6c0bc9c/tibiapi/skills/skills.py#L33

I will do the same strategy like I did to get mana/health: https://github.com/lucasmonstrox/tibiapi/blob/f5fd71202309f5a244fa19fbe4ffbbebc6c0bc9c/tibiapi/statusBar/utils.py#L7

**Comment by Kirattus** [comment]
that's nice! thx for it.

**Comment by lucasmonstrox** [comment]
@Kirattus I already start creating a method to get level percentage, you can see here https://github.com/lucasmonstrox/tibiapi/pull/4. I will add tests today.

**Comment by lucasmonstrox** [comment]
Hey @Kirattus add tests to PR https://github.com/lucasmonstrox/tibiapi/pull/4. it's good for you? Can you see if everything is ok?

The percentages returned will be **[0, 1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 99]**. Is not possible to return 100 because when the next level is reached, the percentage goes to 0.

**Comment by lucasmonstrox** [comment]
@Kirattus added feature in PR https://github.com/lucasmonstrox/tibiapi/pull/5, also fixed creatures names issues.

**Comment by lucasmonstrox** [comment]
@Kirattus already done!

**Comment by Kirattus** [comment]
i'ts work like a charm...
![image](https://github.com/lucasmonstrox/tibiapi/assets/34078319/ed0029ad-3429-4f9f-9c03-7b84edd2cf84)
