### ISSUE TITLE
[FEATURE] - Get speed info on skill container

### ISSUE THREAD

**Issue by Kirattus** [lucasmonstrox/tibiapi#20]
**Is your feature request related to a problem? Please describe.**
not applicable

**Describe the solution you'd like**
return the value of speed character.

**Describe alternatives you've considered**
not applicable

**Additional context**
not applicable

**Comment by lucasmonstrox** [comment]
@Kirattus already implemented, but I need to create PR. Also I need to add some tests. Maybe, I can delivery it today.
