### ISSUE TITLE
[FEATURE] - [Skills] - get a speed value

### ISSUE THREAD

**Issue by raphlmiranda** [lucasmonstrox/tibiapi#22]
Is your feature request related to a problem? Please describe.
-

Describe the solution you'd like
Create a method to return a speed value

Describe alternatives you've considered
-

Additional context
-

**Comment by lucasmonstrox** [comment]
@raphlmiranda already did it yesterday. Duplicate of https://github.com/lucasmonstrox/tibiapi/issues/20.
