### ISSUE TITLE
[FEATURE] - Skills - current exp count

### ISSUE THREAD

**Issue by Kirattus** [lucasmonstrox/tibiapi#6]
**Is your feature request related to a problem? Please describe.**
not applicable

**Describe the solution you'd like**
like the other parts to get numbers, is a good idea to show how much exp is showing on the skills.

**Describe alternatives you've considered**
not applicable

**Additional context**
depending on quantity of numbers, the label "experience" can be shortened by the client to fit in the space.
Experience - if the amout is >= 99,999,999 
Else "XP" above above this.

**Comment by lucasmonstrox** [comment]
I already did, here you can see https://github.com/lucasmonstrox/tibiapi/blob/main/tibiapi/skills/skills.py#L58.

**Comment by Kirattus** [comment]
passed on my test. 
Thx
