### ISSUE TITLE
[FEATURE] - [Skills] - ExpGainRate

### ISSUE THREAD

**Issue by Kirattus** [lucasmonstrox/tibiapi#7]
**Is your feature request related to a problem? Please describe.**
not applicable

**Describe the solution you'd like**
just get the exp gain rate.
in any case, the player just want hunt until they have a x bonuses, or will buy another bonus of lower at x.

**Describe alternatives you've considered**
not applicable

**Additional context**
you can see a base rate by Stamina count (if on green, or not), but not if has a bonus plus.
not applicable

**Comment by lucasmonstrox** [comment]
@Kirattus added this PR https://github.com/lucasmonstrox/tibiapi/pull/8 to implement xp gain rate percentage. What you think? Also added tests for different colours variations.

**Comment by Kirattus** [comment]
That's nice!
About the tests, I think it's good to initially test only the possible colors, orange, gray and green.
too much possibility bcs of World change, events, boost, etc.

**Comment by lucasmonstrox** [comment]
@Kirattus already done!

**Comment by Kirattus** [comment]
perfect!
tested and working.
